"""empty message

Revision ID: 8afff2a54e02
Revises: e44c969270da
Create Date: 2020-06-13 10:42:32.217112

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8afff2a54e02'
down_revision = 'e44c969270da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('authority')
    op.drop_column('application', 'description')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('description', sa.VARCHAR(length=4095), nullable=True))
    op.create_table('authority',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('public_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('application_public_id', sa.VARCHAR(length=255), nullable=True),
    sa.Column('division', sa.VARCHAR(length=255), nullable=True),
    sa.Column('detail', sa.VARCHAR(length=511), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    # ### end Alembic commands ###
